events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name przyczepymalkinia.pl www.przyczepymalkinia.pl;
        root /usr/share/nginx/html;
        index index.html;

        # 1. Przekierowanie z /index lub /index.html na czysty ukośnik /
        if ($request_uri ~* "^/index(\.html)?$") {
            return 301 /;
        }

        # 2. Przekierowanie z pliku.html na wersję bez .html (dla przeglądarek)
        if ($request_uri ~* "^(.+)\.html$") {
            return 301 $1;
        }

        # 3. Wewnętrzne mapowanie (jeśli ktoś wpisze /o-nas, Nginx szuka o-nas.html)
        location / {
            try_files $uri $uri/ $uri.html =404;
        }
    }
}