name: Auto Deploy via GitHub Runner (Nginx Docker)

on:
  push:
    branches:
      - main  # Zmień na master, jeśli Twoja główna gałąź tak się nazywa

jobs:
  deploy:
    runs-on: self-hosted  # Twój obecny lokalny runner to obsłuży

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Kopiowanie plików prosto do folderu, który czyta Nginx w Dockerze
      - name: Sync files directly to Nginx Docker folder
        run: |
          rsync -rlptD -v --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='nginx.conf' \
            --exclude='.idea' \
            ./ ~/strona_www/html/
